version: '3.2'

services:
   db:
     image: mysql:5.7
     container_name: mysql_rian
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: riansakti
       MYSQL_PASSWORD: rahasia

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: wordpress_rian
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: riansakti
       WORDPRESS_DB_PASSWORD: rahasia
volumes:
    dbdata:
